// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjTuqcWOB1arsNNODZz-rHTMaVYrOb2fg',
    appId: '1:609508120266:web:c791e0cfa6345e6ec0c633',
    messagingSenderId: '609508120266',
    projectId: 'fasum-app-675e4',
    authDomain: 'fasum-app-675e4.firebaseapp.com',
    storageBucket: 'fasum-app-675e4.firebasestorage.app',
    measurementId: 'G-BMPZB8427G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGaXeN6PnRsgXWuRrBCiYLwHsGjbWWgjs',
    appId: '1:609508120266:android:09a6c96fa964743cc0c633',
    messagingSenderId: '609508120266',
    projectId: 'fasum-app-675e4',
    storageBucket: 'fasum-app-675e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyp3PbQAAi9qe6Ie-6Lf1bDLoIQlYiZnI',
    appId: '1:609508120266:ios:81cebc8e93b63b34c0c633',
    messagingSenderId: '609508120266',
    projectId: 'fasum-app-675e4',
    storageBucket: 'fasum-app-675e4.firebasestorage.app',
    iosClientId: '609508120266-3l9it79kjrcr65ev3ltpo26rbfeokg2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyp3PbQAAi9qe6Ie-6Lf1bDLoIQlYiZnI',
    appId: '1:609508120266:ios:81cebc8e93b63b34c0c633',
    messagingSenderId: '609508120266',
    projectId: 'fasum-app-675e4',
    storageBucket: 'fasum-app-675e4.firebasestorage.app',
    iosClientId: '609508120266-3l9it79kjrcr65ev3ltpo26rbfeokg2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjTuqcWOB1arsNNODZz-rHTMaVYrOb2fg',
    appId: '1:609508120266:web:0e928b93a53b5d69c0c633',
    messagingSenderId: '609508120266',
    projectId: 'fasum-app-675e4',
    authDomain: 'fasum-app-675e4.firebaseapp.com',
    storageBucket: 'fasum-app-675e4.firebasestorage.app',
    measurementId: 'G-6EZJ68K60V',
  );
}
